$WALLPAPER_PATH = ~/nixos-dotfiles/icons/wallpaper/wallpaper2.jpg

background {
    path = $WALLPAPER_PATH
    blur_passes = 0
    contrast = 0.5
    brightness = 0.5
    vibrancy = 0.1695
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 5
    fail_timeout = 6000
    disable_loading_bar = false
    hide_cursor = true
}

input-field {
    monitor =
    size = 500, 80
    outline_thickness = 0
    dots_size = 0.5
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(211, 198, 170)
    inner_color = rgba(0, 0, 0, 0)
    dots_text_format = *
    font_color = rgb(211, 198, 170)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = Enter your password bitch
    hide_input = false
    position = 0, -350
    halign = center
    valign = center
    check_color = rgba(0, 0, 0, 0)
    fail_text = You entered the wrong password you fucking loser. Go kill yourelf. 
    fail_color = rgba(230, 126, 128, 1)
    capslock_color = rgb(230, 126, 128)
    swap_font_color = true
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgb(211, 198, 170)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 310
    halign = center
    valign = center
}

label {
    monitor =
    text =cmd[update:1000] echo battery"<span>$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage)</span>"
    color = rgb(211, 198, 170)
    font_size = 8
    font_family = Jet Brains Mono
    position = 800, -500
}
